# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZER0trace Internal' do
	pod 'LLSimpleCamera', '~> 4.1'
	pod 'Firebase/Core'
	pod 'Firebase/Storage'
	pod 'Firebase/Database'
	pod 'QRCodeReaderViewController', '~> 4.0.2’
	pod ‘CTVideoPlayerView’

end
