# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZER0trace External' do
  	pod 'Firebase/Core'
	pod 'Firebase/Storage'
	pod ‘CTVideoPlayerView’

end
